Repository smartcoop/smart-cfa, pull requests merged in 2022-05, with the labels that each got.

#117 UserAdmin: TrainingList: Move the "You don't have any trainings yet" message higher on the screen
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
Labels: enhancement

#120 Move submit button of training creation, edition pages and profile édition page inside the navbar
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
Labels: enhancement

#119 Disable event on key enter pressed on form in training creation and edition pages
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
Labels: bug

#115 Fix an issue where switch from training's status from validated to draft wouldn't work
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/CreateTrainingCommandHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Enumerations/VatExemptionClaimExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/Training.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/UpdateTrainingViewModel.cs
  src/UserAdmin/test/Smart.FA.Catalog.UnitTests/Training_Tests.cs
Labels: bug

#130 Fix an issue where Domain Event could not be property published
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Persistence/CatalogContext.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Services/DomainEventPublisher.cs
Labels: bug

#134 Fix an error introduced with #130
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Services/DomainEventPublisher.cs
Labels: bug

#128 Standarize paging super user
  src/Shared/Smart.FA.Catalog.Shared/Collections/PagedList.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetPagedTrainingListFromTrainerQueryHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsByCriteriaQuery.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Extensions/PagedListExtension.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml.cs
Labels: bug

#131 Add special authentication options for using fake headers
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Options/SpecialAuthenticationOptions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json
Labels: enhancement

#132 Add SQL 2008 fix to showcase
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Program.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Smart.FA.Catalog.Showcase.Web.csproj
Labels: bug

#136 Add explictely authorization options in appsettings.Production
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
Labels: bug

#137 ProfileViewModels: socialNetwork mapping: don't encapsulate parsing in a try-catch but check if name exists
  src/UserAdmin/src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs
Labels: enhancement

#138 Add support for searching trainers in the Showcase project
  src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/Partials/TrainerList.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainerList.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainerQueryableExtensions.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Scripts/v_TrainerList.sql
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Mappers/TrainerMapper.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Trainer/ITrainerService.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Trainer/TrainerService.cs
Labels: enhancement

#142 CreateTrainingRequestValidator: add missing translation for training title validation
  src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/CreateTrainingRequestValidator.cs
Labels: bug

#146 Replace forwardslash by backslash in nlog logging file
  src/UserAdmin/src/Smart.FA.Catalog.Web/nlog.config
Labels: enhancement

#129 Persist the first name, last name and email address of a trainer using data sent by account in the HTTP headers
  nginx.conf
  src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/AccountData.cs
  src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/AccountDataHeaderSerializer.cs
  src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/IAccountDataHeaderSerializer.cs
  src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/Pages/cfa.cshtml.cs
  src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/Program.cs
  src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/ProxyHeaderMiddleware.cs
  src/AccountSimulator/src/Smart.FA.Catalog.AccountSimulator/ProxyRedirect.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/CreateTrainerFromUserAppCommandHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainerIdentityCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainerFromUserAppQueryHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/User/Dto/UserDto.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Services/FakeAccountUserStrategy.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Handlers/UserAdminAuthenticationHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/AccountData.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/AccountDataHeaderHeaderSerializer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/AccountHeadersValidator.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/Headers.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authentication/Header/IAccountDataHeaderSerializer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs
  src/UserAdmin/test/Smart.FA.Catalog.IntegrationTests/TrainingContext/Trainer_Tests.cs
  src/UserAdmin/test/Smart.FA.Catalog.IntegrationTests/TrainingContext/User_Tests.cs
  src/UserAdmin/test/Smart.FA.Catalog.Tests.Common/UserFactory.cs
Labels: enhancement

#141 Replace pre-signed image by public url
  src/UserAdmin/src/Smart.FA.Catalog.Application/Extensions/ProfilePictureExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/DeleteTrainerProfileImageCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UploadTrainerProfileImageCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetLatestUserChartRevisionUrlQuery.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainerProfileQuery.cs
  src/UserAdmin/src/Smart.FA.Catalog.Core/Extensions/UserChartRevisionExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/IMinIoLinkGenerator.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Services/BootStrapService.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Smart.FA.Catalog.Infrastructure.csproj
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Development.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.PreProduction.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Staging.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json
Labels: enhancement

#144 Log properly exceptions
  src/UserAdmin/src/Smart.FA.Catalog.Application/Interceptors/LoggingPipelineBehavior.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/DeleteTrainingCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainersFromTrainingQueryHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingFromIdQueryHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsFromTrainerQueryHandler.cs
Labels: enhancement

#143 Prevent invalid operation when approving an already approved user chart revision
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/SetTrainerHasAcceptedLatestUserChartRevisionCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Trainer/Trainer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml.cs
Labels: bug

#147 LoggingPipelineBehavior: don't log Trainer nor Training domain models that transit through MediatR
  src/UserAdmin/src/Smart.FA.Catalog.Application/Interceptors/LoggingPipelineBehavior.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/SuperUserJsonConverter.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/TrainerAssignmentJsonConverter.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/TrainerJsonConverter.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/TrainingJsonConverter.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/UserChartRevisionJsonConverter.cs
Labels: bug, enhancement

#150 Fix build compilation due to wrong merge
  src/UserAdmin/src/Smart.FA.Catalog.Application/SeedWork/Json/Converters/SuperUserJsonConverter.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/UserChart.cshtml.cs
Labels: bug

#116 Only creators and super users must be able to edit a training
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UpdateTrainingCommandHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Handlers/UserAdminAuthorizationResultHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Policies.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Policy/Requirements/MustBeSuperUserOrTrainingCreator.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/MvcBuilderExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml.css
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/AdminPage.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/PageModelBase.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Validators/UpdateTrainingRequestValidator.cs
Labels: bug

#154 Fix redirection to not found page
  src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
Labels: bug

#156 Fix label of maximum length of presentation and goal fields on training creation and update page
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
Labels: bug

#166 Showcase: display a message when no trainers were found
  src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.Designer.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Localization/ShowcaseResources.resx
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
Labels: enhancement

#152 Add a 'cfa' base path to user admin URL so the website works with nginx
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
  src/UserAdmin/src/Smart.FA.Catalog.Web/Authorization/Handlers/UserAdminAuthorizationResultHandler.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/ServiceCollectionExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Options/UrlOptions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/404.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/SideMenuItems.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Index.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Routes.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Program.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Development.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.PreProduction.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Staging.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json
Labels: bug, enhancement

#165 Add random salt to trainer profile picture
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
Labels: enhancement

#149 Display a success message creation edition training
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
  src/UserAdmin/src/Smart.FA.Catalog.Web/Extensions/GlobalBannerMessageTempDataDictionaryExtensions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Create/Index.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/Update/Index.cshtml.cs
Labels: enhancement

#164 Showcase: add support to fetch images from minio
  src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainerDetails.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingDetails.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Domain/Models/TrainingList.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/PaginationExtensions.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Infrastructure/Data/Extensions/TrainingQueryableExtensions.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Constants.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Mappers/TrainerMapper.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Options/MinIOOptions.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Shared/_TrainingTitle.cshtml
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetailsViewModel.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Program.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Trainer/ITrainerService.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Trainer/TrainerService.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/appsettings.PreProduction.json
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/appsettings.Production.json
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/appsettings.json
Labels: enhancement

#170 Surround global banner on training listing page with a o-container
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainings/List/Index.cshtml
Labels: bug

#169 Update HTML of usermenu to match account
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_AdminLayout.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/_Layout.cshtml
Labels: enhancement

#173 Make URL of Showcase website customizable accordingly to underlying environment
  src/UserAdmin/src/Smart.FA.Catalog.Web/Options/UrlOptions.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Index.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.PreProduction.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.json
Labels: enhancement

#179 Add implicit conversion to string on Name value object
  src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/ValueObjects/Name.cs
Labels: enhancement

#189 Conserve line breaks in training and trainer description
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Extensions/HtmlExtensions.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerDetails/TrainerDetails.cshtml
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Trainer/TrainerList/TrainerList.cshtml
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingDetails/TrainingDetails.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/wwwroot/js/lib.js
Labels: bug

#180 UserAdmin: SuperUserTrainingList: add support for searching trainings by training creator name
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Queries/GetTrainingsByCriteriaQuery.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/AdminTrainingCardViewComponent.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Shared/Components/AdminTrainingTile/Default.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/SuperUser/Trainings/List/SuperUserTrainingList.cshtml
Labels: enhancement

#187 Rewrite minio handler
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/EditProfileCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Application/UseCases/Commands/UploadTrainerProfileImageCommand.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Helpers/MinIoLinkGenerator.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.Designer.cs
  src/UserAdmin/src/Smart.FA.Catalog.Localization/CatalogResources.resx
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml
  src/UserAdmin/src/Smart.FA.Catalog.Web/Pages/Admin/Trainers/Profile.cshtml.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/ViewModels/Trainers/ProfileViewModels.cs
Labels: enhancement

#193 Filter out unpublished trainings
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Pages/Training/TrainingList/TrainingList.cshtml.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Training/ITrainingService.cs
  src/Showcase/src/Smart.FA.Catalog.Showcase.Web/Services/Training/TrainingService.cs
Labels: bug

#192 Organize solution items and dockerfiles (no renaming)
  Jenkinsfile
  Minio.Dockerfile
  Nginx.Dockerfile
  Showcase.Dockerfile
  Smart.FA.Catalog.sln
  Web.Dockerfile
  docker-compose-local.yml
  docker-compose-nginx.yml
  docker-compose-startup.yml
  docker-compose.yml
  docker/.dockerignore
  docker/.env
  docker/DB.Dockerfile
  docker/Showcase.Dockerfile
  docker/Web.Dockerfile
  docker/kerberos/Showcase.krb5.Dockerfile
  docker/kerberos/Web.krb5.Dockerfile
  docker/nginx/AccountSim.Dockerfile
  docker/nginx/Nginx.Dockerfile
  docker/nginx/nginx.conf
  pipeline-scripts/Jenkinsfile
  pipeline-scripts/deploy-prod.sh
  pipeline-scripts/deploy-staging.sh
  pipeline-scripts/jenkins-deploy.sh
  pipeline-scripts/ktutil/Dockerfile
  pipeline-scripts/ktutil/cfa-cron
  pipeline-scripts/ktutil/files/krb5.conf
  pipeline-scripts/ktutil/files/smartserver_DEV.keytab
  pipeline-scripts/ktutil/ktutil.sh
  pipeline-scripts/ktutil/refresh.sh
  pipeline-scripts/ktutil/run.sh
  pipeline-scripts/launch_showcase.sh
  pipeline-scripts/launch_useradmin.sh
  src/UserAdmin/src/Smart.FA.Catalog.Core/Domain/Training/VatExemptionClaim.cs
  src/UserAdmin/src/Smart.FA.Catalog.Infrastructure/Migrations/ContextModelSnapshot.cs
  src/UserAdmin/src/Smart.FA.Catalog.UserAdmin.Infrastructure/Persistence/Migrations/20220518184922_Set_DateTime_To_3_Precision.Designer.cs
  src/UserAdmin/src/Smart.FA.Catalog.UserAdmin.Infrastructure/Persistence/Migrations/20220518184922_Set_DateTime_To_3_Precision.cs
  src/UserAdmin/src/Smart.FA.Catalog.Web/appsettings.Production.json
  startup-scripts/docker_startup_script.bat
  startup-scripts/startup.bat
Labels: enhancement
